"use strict";

module.exports = function (grunt) {
  // Load grunt tasks automatically.
  require('load-grunt-tasks')(grunt, {pattern: ['grunt-*']});

  // Time how long tasks take. Can help when optimizing build times
  require('time-grunt')(grunt);

  grunt.initConfig({
    compass: {
      build: {
        options: {
          config: "compass.rb",
          bundleExec: true
        }
      }
    },
    'compile-handlebars': {
      src: {
        template: 'src/templates/index.handlebars',
        templateData: 'config/config.json',
        output: 'src/index.html'
      }
    },
    watch: {
      /*bower: {
        files: ['bower.json','./src/index.html'],
        tasks: ['wiredep']
      },*/
      browserify: {
        files: [
          './config/config.js',
          './config/config.json'
        ],
        tasks: ['browserify:config']
      },
      config: {
        files: [
          './src/templates/*.handlebars',
          './src/templates/**/*.handlebars',
          './config/config.json'
        ],
        tasks: ['compile-handlebars:src']
      },
      compass: {
        files: ['src/**/*.{scss,sass}'],
        tasks: ['compass']
      },
      jshint: {
        files: ['config/config.js'],
        tasks: ['jshint']
      },
      livereload: {
        files: [
          'src/templates/index.handlebars',
          'src/index.html',
          'src/config/config.json',
          'src/**/*.css',
          'src/**/*.js',
          'src/img/{,*//*}*.{png,jpg,jpeg,gif,webp,svg}'
        ],
        options: {
          livereload: true
        }
      }
    },
    browserify: {
      options: {
          browserifyOptions: {
            standalone: "ReliefwebWidgets"
          }
      },
      config: {
        src: './config/config.js',
        dest: './src/js/browserfy.config.js'
      }
    },
    // All other files were generated by browserfy or handlebars.
    jshint: {
      all: [
        'config/config.js',
      ]
    },
    connect: {
      default: {
        options: {
          base: 'src',
          port: 9001,
          open: true,
          livereload: true,
          middleware: function (connect, options, middlewares) {
            middlewares.unshift(function(req, res, next) {
              res.setHeader('Access-Control-Allow-Origin', '*');
              res.setHeader('Access-Control-Allow-Methods', '*');
              next();
            });

            return middlewares;
          }
        }
      },
      dist: {
        options: {
          base: 'dist',
          port: 9001,
          open: true,
          keepalive: true,
          middleware: function (connect, options, middlewares) {
            middlewares.unshift(function(req, res, next) {
              res.setHeader('Access-Control-Allow-Origin', '*');
              res.setHeader('Access-Control-Allow-Methods', '*');
              next();
            });

            return middlewares;
          }
        }
      }
    },
    shell: {
      collect: {
        command: 'bin/collect | node_modules/.bin/bunyan'
      }
    },
    clean: {
      dist: [ 'dist' ]
    },
    copy: {
      dist: {
        files: [
          {
            expand: true,
            src: [ 'img/**', 'fonts/**', 'index.html' ],
            dest: 'dist',
            cwd: 'src'
          }
        ]
      },
      config: {
        files: [
          {
            src: [ 'config/config.json' ],
            dest: 'dist/config.json'
          },
          {
            expand: true,
            src: [ '*' ],
            dest: 'dist/config',
            cwd: 'config/config'
          }
        ]
      }
    },
    useminPrepare: {
      html: 'src/index.html',
      options: {
        dest: 'dist'
      }
    },
    usemin: {
      html: ['dist/*.html']
    }
  });

  grunt.registerTask('default', [
    'compass',
    'shell:collect',
    'compile-handlebars:src',
    'jshint',
    'browserify'
  ]);

  grunt.registerTask('build', ['default']);

  grunt.registerTask('watchSrc', [
    'default',
    'connect:default',
    'watch'
  ]);

  grunt.registerTask('release', [
    'clean',
    'default',
    'useminPrepare',
    'concat',
    'uglify',
    'cssmin',
    'copy:dist',
    'copy:config',
    'usemin'
   ]);

  grunt.registerTask('serve', [
    'connect:dist'
  ]);

  grunt.registerTask('start', [
    'release',
    'serve'
  ]);
};
